name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install MinGW-w64
      run: |
        choco install mingw
        refreshenv

    - name: Install SDL2 dependencies
      run: |
        mingw-get install mingw32-libSDL2 mingw32-libSDL2_ttf mingw32-libSDL2_image mingw32-libSDL2_mixer

    - name: Build
      run: |
        gcc -o main main.c map.c -I"C:\MinGW\include" -L"C:\MinGW\lib" -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf -lSDL2_image -lSDL2_mixer

    - name: Test
      run: main.exe

    - name: Distcheck
      run: echo "Perform distcheck here if needed"
