name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install SDL2 dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev

    - name: Install SDL2_TTF dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-ttf-dev

    - name: Install SDL2_image dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-image-dev

    - name: Install SDL2_mixer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-mixer-dev

    - name: Build
      run: make

    - name: Test
      run: make check

    - name: Distcheck
      run: make distcheck
