name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install SDL2 dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev

    - name: Build
      run: |
        gcc -I src/include -L src/lib -o main main.c map.c -lSDL2main -lSDL2 -lSDL2_TTF -lSDL2_image -lSDL2_mixer

    - name: Test
      run: make check

    - name: Distcheck
      run: make distcheck
